name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
  workflow_dispatch:


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches/
          key: build-${{ hashFiles('**/build.gradle.kts') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/src/main/java/Dependencies.kt') }}

      - name: Build
        run: ./gradlew build check publishToMavenLocal --continue --warning-mode all


  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches/
          key: unit-tests-${{ hashFiles('**/build.gradle.kts') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/src/main/java/Dependencies.kt') }}

      - name: Unit tests
        run: ./gradlew testDebugUnitTest


  instrumentation-tests:
    name: Instrumentation tests
    runs-on: macOS-latest
    timeout-minutes: 60
    strategy:
      fail-fast: true
      matrix:
        api-level: [21, 23, 25, 27, 29]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: instrumentation-tests-${{ hashFiles('**/build.gradle.kts') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/src/main/java/Dependencies.kt') }}

      - name: Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86
          script: ./gradlew connectedDebugAndroidTest
